version: '3.4'

services:
  poc_orm_netcore:
    image: ${DOCKER_REGISTRY-}pocormnetcore
    build:
      context: .
      dockerfile: src/POC_ORM_NetCore/Dockerfile
    entrypoint: ["/wait-for-it.sh", "sqlserver:1434", "--", "dotnet", "POC_ORM_NetCore.dll"]
  sqlserver:
    image: microsoft/mssql-server-linux
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=@Passw0rd
      - ACCEPT_EULA=Y